name: Build/release

on: 
  workflow_dispatch:
  push:
    tags: 
      - v1.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Yarn make
        run: |
             yarn
             yarn make
             ls -R out/make/zip
        
